apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rushikesh-cluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20