---
apiVersion: v1
kind: Service
metadata:
  name: data-processing-service
  namespace: data-processing
spec:
  type: LoadBalancer
  selector:
    app: data-processing-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 